In [1]:
import numpy as np

In [2]:
l=[1,3,5,7,9]

In [3]:
arr=np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 3, 5, 7, 9])

In [6]:
arr1=np.array([[1,3,5,7,9],[2,4,6,8,0]])

In [7]:
arr.ndim

1

In [8]:
arr1.ndim

2

In [9]:
arr1

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0]])

In [10]:
mat=np.matrix(l)

In [11]:
np.asanyarray(l)

array([1, 3, 5, 7, 9])

In [12]:
np.asanyarray(mat)

matrix([[1, 3, 5, 7, 9]])

In [13]:
a=arr #shallow copying

In [14]:
a

array([1, 3, 5, 7, 9])

In [15]:
arr

array([1, 3, 5, 7, 9])

In [16]:
arr[0]=100

In [17]:
arr

array([100,   3,   5,   7,   9])

In [18]:
a

array([100,   3,   5,   7,   9])

In [19]:
b=np.copy(arr) ##deep copy

In [20]:
b

array([100,   3,   5,   7,   9])

In [21]:
b[1]=300

In [22]:
b

array([100, 300,   5,   7,   9])

In [23]:
arr

array([100,   3,   5,   7,   9])

In [24]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [25]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [26]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [27]:
iterable=(i*i for i in range (5))

In [28]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [29]:
np.fromstring('11 24 29',sep=' ' )

array([11., 24., 29.])

In [30]:
np.fromstring('11,24,29',sep=',')

array([11., 24., 29.])

In [31]:
arr

array([100,   3,   5,   7,   9])

In [32]:
arr1

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0]])

In [33]:
arr.size

5

In [34]:
arr1.size

10

In [35]:
arr.shape

(5,)

In [36]:
arr1.shape

(2, 5)

In [37]:
arr.dtype

dtype('int64')

In [38]:
arr1.dtype

dtype('int64')

In [39]:
import numpy as np

In [40]:
list(range(5))

[0, 1, 2, 3, 4]

In [41]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
list(range(0.5,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [43]:
np.arange(.5,10.5)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [44]:
np.arange(.5,10.5,.5)

array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [45]:
list(np.arange(.5,10.5,.5))

[0.5,
 1.0,
 1.5,
 2.0,
 2.5,
 3.0,
 3.5,
 4.0,
 4.5,
 5.0,
 5.5,
 6.0,
 6.5,
 7.0,
 7.5,
 8.0,
 8.5,
 9.0,
 9.5,
 10.0]

In [46]:
np.linspace(1,5 , 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [47]:
np.logspace(1,5 , 10,2)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])

In [50]:
np.zeros((3,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [51]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [52]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [53]:
arr=np.ones((3,4))

In [54]:
arr+11

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.]])

In [55]:
arr1=np.eye(5)

In [56]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
import pandas as pd

In [58]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [59]:
np.random.rand(2,3)

array([[0.96820583, 0.49896375, 0.10997296],
       [0.27696725, 0.02755475, 0.79003945]])

In [60]:
np.random.randn(2,3) ##here mean=0,standarddeviation=1 

array([[ 0.72336271, -0.07871116,  1.07744133],
       [-0.51211629, -0.34458292, -0.48300563]])

In [61]:
arr2=np.random.randint(1,10,(3,4))

In [62]:
arr2.size

12

In [63]:
arr2.shape

(3, 4)

In [64]:
arr2.reshape(6,2)

array([[3, 3],
       [9, 8],
       [2, 6],
       [8, 4],
       [6, 1],
       [3, 7]])

In [65]:
arr2.reshape(2,6)

array([[3, 3, 9, 8, 2, 6],
       [8, 4, 6, 1, 3, 7]])

In [66]:
arr2.reshape(2,6)

array([[3, 3, 9, 8, 2, 6],
       [8, 4, 6, 1, 3, 7]])

In [67]:
arr2.reshape(4,3)

array([[3, 3, 9],
       [8, 2, 6],
       [8, 4, 6],
       [1, 3, 7]])

In [68]:
arr2.reshape(4,-1)

array([[3, 3, 9],
       [8, 2, 6],
       [8, 4, 6],
       [1, 3, 7]])

In [69]:
arr2.reshape(3,-1) ##any negative no

array([[3, 3, 9, 8],
       [2, 6, 8, 4],
       [6, 1, 3, 7]])

In [70]:
arr3=np.random.randint(0,10,(5,6))

In [71]:
arr3>7

array([[False,  True, False, False,  True, False],
       [False, False, False,  True,  True, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False],
       [False, False,  True, False, False, False]])

In [72]:
arr3[arr3>7]

array([8, 8, 8, 8, 9, 9])

In [73]:
arr3

array([[3, 8, 5, 2, 8, 0],
       [0, 1, 5, 8, 8, 2],
       [2, 0, 2, 3, 1, 4],
       [0, 5, 0, 5, 9, 7],
       [3, 6, 9, 0, 2, 6]])

In [74]:
arr3[0]

array([3, 8, 5, 2, 8, 0])

In [75]:
arr3[0,[0,1]]

array([3, 8])

In [76]:
arr3[2:3,[2,3]]

array([[2, 3]])

In [77]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [78]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [79]:
arr2

array([[2, 2, 2],
       [1, 2, 2],
       [1, 1, 1]])

In [80]:
arr1+arr2

array([[4, 3, 3],
       [3, 3, 3],
       [3, 2, 3]])

In [81]:
arr1*arr2 ##this is not matrix multiplication

array([[4, 2, 2],
       [2, 2, 2],
       [2, 1, 2]])

In [82]:
arr1@arr2

array([[6, 7, 7],
       [6, 7, 7],
       [7, 8, 8]])

In [83]:
##broadcasting

In [84]:
arr=np.zeros((3,4))

In [85]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [86]:
a=np.array([1,2,3,4])

In [88]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [87]:
b=np.array([[2,3,4]])

In [ ]:
arr1=arr+b.T

In [89]:
b.T

array([[2],
       [3],
       [4]])

In [90]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [91]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.        ],
       [1.41421356, 1.        , 1.        ],
       [1.41421356, 1.        , 1.41421356]])

In [92]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [ ]:
np.log10(arr1)

array([[0.30103   , 0.30103   , 0.30103   , 0.30103   ],
       [0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999]])

In [93]:
#array manipulation

In [ ]:
arr=np.random.randint(1,10,(4,4))

In [94]:
arr.reshape(8,2)

ValueError: cannot reshape array of size 12 into shape (8,2)

In [95]:
arr.T

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [96]:
arr.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [97]:
np.expand_dims(arr,axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [98]:
np.expand_dims(arr,axis=2)

array([[[0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.]]])

In [99]:
data=np.array([[1],[2],[3]])

In [100]:
np.squeeze(data)

array([1, 2, 3])

In [101]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [102]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [103]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [104]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [105]:
arr1=np.random.randint(1,10,(4,4))

In [106]:
arr1**2

array([[81,  9, 49,  4],
       [81, 64, 36,  1],
       [ 1, 49, 25,  1],
       [81, 16, 81, 49]])

In [107]:
~arr1

array([[-10,  -4,  -8,  -3],
       [-10,  -9,  -7,  -2],
       [ -2,  -8,  -6,  -2],
       [-10,  -5, -10,  -8]])

In [108]:
arr1

array([[9, 3, 7, 2],
       [9, 8, 6, 1],
       [1, 7, 5, 1],
       [9, 4, 9, 7]])

In [109]:
np.sin(arr1)

array([[ 0.41211849,  0.14112001,  0.6569866 ,  0.90929743],
       [ 0.41211849,  0.98935825, -0.2794155 ,  0.84147098],
       [ 0.84147098,  0.6569866 , -0.95892427,  0.84147098],
       [ 0.41211849, -0.7568025 ,  0.41211849,  0.6569866 ]])

In [110]:
np.tan(arr1)

array([[-0.45231566, -0.14254654,  0.87144798, -2.18503986],
       [-0.45231566, -6.79971146, -0.29100619,  1.55740772],
       [ 1.55740772,  0.87144798, -3.38051501,  1.55740772],
       [-0.45231566,  1.15782128, -0.45231566,  0.87144798]])

In [111]:
np.power(arr1,4)

array([[6561,   81, 2401,   16],
       [6561, 4096, 1296,    1],
       [   1, 2401,  625,    1],
       [6561,  256, 6561, 2401]])

In [112]:
np.mean(arr1)

5.5

In [113]:
np.median(arr1)

6.5

In [114]:
np.std(arr1)

3.0

In [115]:
np.var(arr1)

9.0

In [116]:
##sort,search and counting

In [117]:
arr=np.array([1,24,29,14,22,7,5])

In [118]:
np.sort(arr)

array([ 1,  5,  7, 14, 22, 24, 29])

In [119]:
np.searchsorted(arr,29)

7

In [120]:
arr1=np.array([0,1,3,4,67,7785,9880,0,2340,9,8,0,4])

In [121]:
np.count_nonzero(arr1)

10

In [122]:
np.where(arr1>0)

(array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 12]),)

In [123]:
np.where(arr1>2)

(array([ 2,  3,  4,  5,  6,  8,  9, 10, 12]),)

In [124]:
np.extract(arr1>2,arr1)

array([   3,    4,   67, 7785, 9880, 2340,    9,    8,    4])

In [125]:
arr1.byteswap(True)

array([                   0,    72057594037927936,   216172782113783808,
         288230376151711744,  4827858800541171712,  7574491623283752960,
       -7483293730829500416,                    0,  2596606660155801600,
         648518346341351424,   576460752303423488,                    0,
         288230376151711744])

In [126]:
import numpy.matlib as nm 

In [127]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [128]:
nm.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [129]:
arr1= np.random.randint([[2,3],[4,5]])

In [130]:
arr2= np.random.randint([[5,3],[2,5]])

In [131]:
arr1

array([[1, 0],
       [3, 2]])

In [132]:
arr2

array([[2, 2],
       [1, 0]])

In [133]:
np.dot(arr1,arr2)

array([[2, 2],
       [8, 6]])

In [134]:
arr1@arr2

array([[2, 2],
       [8, 6]])